# Generated by Django 3.1.5 on 2021-10-05 16:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='회원ID')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='핸드폰번호')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='카테고리번호')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='카테고리명')),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='번호')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('myself', models.TextField(blank=True, null=True, verbose_name='자기소개')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('sub_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='구독권 번호')),
                ('sub_name', models.CharField(max_length=10, verbose_name='구독권명')),
                ('sub_price', models.IntegerField(verbose_name='구독권금액')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False, verbose_name='결제번호')),
                ('price', models.IntegerField(verbose_name='결제금액')),
                ('card_payment', models.CharField(choices=[('FALSE', 'FALSE'), ('TRUE', 'TRUE'), ('선택안함', '선택안함')], default='N', max_length=10, verbose_name='카드결제여부')),
                ('bank_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='계좌번호')),
                ('pay_date', models.DateTimeField(blank=True, verbose_name='결제일')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='이용시작일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원번호')),
                ('sub_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandwich.subscription', verbose_name='구독권번호')),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='잡지번호')),
                ('title', models.CharField(db_index=True, max_length=45, verbose_name='잡지제목')),
                ('image', models.ImageField(blank=True, null=True, upload_to='magazine_img/%Y/%m/%d', verbose_name='대표이미지')),
                ('info', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('file', models.ImageField(blank=True, null=True, upload_to='pdf/', verbose_name='PDF 첨부파일')),
                ('available_display', models.BooleanField(default=True, verbose_name='Display')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sandwich.category', verbose_name='카테고리')),
                ('editor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandwich.editor', verbose_name='에디터')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('inquiry_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='조회번호')),
                ('inquiry_date', models.DateTimeField(blank=True, verbose_name='다운로드일')),
                ('author_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원번호')),
                ('magazine_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandwich.magazine', verbose_name='잡지번호')),
            ],
        ),
    ]
