# Generated by Django 3.1.5 on 2021-10-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwich', '0002_auto_20211006_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazine',
            old_name='category_id',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='magazine',
            old_name='editor_id',
            new_name='eid',
        ),
        migrations.AlterField(
            model_name='editor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='번호'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='잡지번호'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='card_payment',
            field=models.CharField(choices=[('선택안함', '선택안함'), ('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='N', max_length=10, verbose_name='카드결제여부'),
        ),
    ]
