# Generated by Django 3.1.5 on 2021-07-24 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='게시판번호')),
                ('board_name', models.CharField(max_length=20, verbose_name='게시판이름')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_no', models.AutoField(primary_key=True, serialize=False, verbose_name='게시글 번호')),
                ('post_title', models.CharField(max_length=20, verbose_name='제목')),
                ('post_contents', models.TextField(verbose_name='내용')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='아이디')),
                ('board_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board', verbose_name='게시판 유형')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/', verbose_name='첨부파일명')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_no', models.AutoField(primary_key=True, serialize=False, verbose_name='댓글번호')),
                ('comment_contents', models.TextField(verbose_name='댓글내용')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원ID')),
                ('post_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.post', verbose_name='게시글번호')),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
    ]
